// This is the BlankIndex component.
// It is the top-level component so it is being rendered as the Index page.

import Head from 'next/head'
import { useEffect } from 'react'
import {
  BlankButton,
  BlankLayout,
  NewWindowLink,
  TWCenteredContent
} from '../components'

const Index = () => {
  useEffect(() => {
    const countElement = document.getElementById('canvas-count');
    const current = 5000;
    const total = 10000;
    let count = total;
    let timeouts = [];
  
    const tick = () => {
      count = parseInt(countElement.innerHTML);
      if (count <= current) count = current + 1;
      countElement.innerHTML = `${count - 1}`;
  
      if (count > current + 1) {
        let time = 4;
        timeouts.push(setTimeout(tick, time));
        timeouts.push(setTimeout(tick, time));
      }
    }
  
    tick();
    
    return () => {
      for (const timeout of timeouts) {
        window.clearTimeout(timeout);
      }
    };
  }, []);

  return (
    <div>
      <Head>
        <title>Blank.Foundation</title>
        <meta name="description" content="Generated by NextTemplate" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BlankLayout>
        <TWCenteredContent>
          <div className='container md:flex sm:w-full xl:w-3/4 sm:mx-auto'>
            <div className="mx-auto mb-12 flex flex-none bg-center bg-contain bg-no-repeat text-center text-md tracking-widest" style={{width: "360px", height: "330px", backgroundImage: `url("/nft.png")`}}>
              <div className="m-auto">
                <div><span id="canvas-count">10000</span> / 10000</div>
                <div className="text-gray-500 pt-3">Remaining</div>
              </div>
            </div>
            <div className="flex-none mx-auto w-11/12 md:w-1/2 my-12 md:my-12">
              <h1 className="text-2xl mb-6 font-semibold">United by a blank canvas</h1>
              <p className="text-md mb-6">
                Blank is a collection of 10,000 Blank NFTs that will evolve based on a vote
                of Blank NFT holders. The first 1,000 people to join the community will be
                whitelisted to mint Blank NFTs for free.
              </p>
              <p className="text-md">
                To purchase, apply in Discord.
              </p>
      
              <BlankButton>
                <NewWindowLink
                  href="https://discord.gg/EvyXJHxJaw"
                >
                  Apply
                </NewWindowLink>
              </BlankButton>
      
              <BlankButton
                classMap={{
                  paddingX: "px-9",
                  marginLeft: "ml-6"
                }}
              >
                <NewWindowLink
                  href="https://medium.com/@blankfdn"
                >
                  Learn More
                </NewWindowLink>
              </BlankButton>
            </div>
          </div>
        </TWCenteredContent>
      </BlankLayout>
    </div>
  );
}

export default Index;