// This is the BlankIndex component.
// It is the top-level component so it is being rendered as the Index page.

import Head from 'next/head'
import {
  BlankLayout,
  TWCenteredContent,
  NextLink
} from './_components'

const Index = () => {
  return (
    <div>
      <Head>
        <title>Blank.Foundation</title>
        <meta name="description" content="Generated by NextTemplate" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BlankLayout>
        <TWCenteredContent>
          <p>CONTENT!</p>
          <p>
            <NextLink 
              href='/mint' 
              passHref
            >
              <a className='text-blue-500 underline'>
                Mint!
              </a>
            </NextLink>
          </p>
        </TWCenteredContent>
      </BlankLayout>
    </div>
  );
}

export default Index;